config/routes.rb
Rails.application.routes.draw do

  match '/admin/movies' => 'movies#create', via: :post

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  # devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks", confirmations: "confirmations" }
  # as :user do
  #    get 'login' => 'sessions#new', :as => "login"
  #    get 'signup' => 'registrations#new', :as => "signup"
  #    get 'signout' => 'devise/sessions#destroy', :as => "signout"
  # end
    resources :movies,:except => [:new, :delete,:edit,:update] do
      resources :comments
      collection do
        get 'browse', to: 'movies#browse'
      end
    end

  root 'movies#index'
end

app/views/shared/_header.html.erb
<script>
$('.carousel').carousel({
    pause: "false" /* Change to true to make it paused when your mouse cursor enter the background */
});
</script>

<div class="container-fluid main">
    <nav class="navbar navbar-default">
      <div class = "container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
             <!-- <span class="sr-only">Toggle navigation</span> -->
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
          </button>
          <%= link_to 'Home', movies_path, :class=>"navbar-brand"%>
        </div>

        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class = "nav navbar-nav">
          <%= form_tag(browse_movies_path, :method => "get", id: "search-form", :class => "navbar-form navbar-left navbar-brand form-group") do %>
              <li><span class="glyphicon glyphicon-search searcharea"></span>
              <%= text_field_tag :search, params[:search], placeholder: "Search Movies",:class => "form-control searchfield form-group"  %>
              <%= submit_tag "Search",class:"btn btn-default searchbutton" %></li>
          <% end %>
        </ul>


        <% if !user_signed_in?%>
        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <a href="<%= new_user_registration_path%>">Sign Up</a>
          </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">More:  <strong class="caret"></strong></a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="<%=new_user_session_path%>">Sign In</a>
                    </li>
                    <li class="divider">
                    </li>
                    <li>
                      <a href="#">Separated link</a>
                    </li>
                  </ul>
            </li>
          </ul>
          <%end %>
          <% if user_signed_in?%>
          <ul class="nav navbar-nav navbar-right">
             <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Options:  <strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="#">Profile</a>
                      </li>
                      <li>
                        <a href="<%= edit_user_registration_path %>">Account Settings</a>
                      </li>

                      <li class="divider">
                      </li>
                      <li>
                        <li><%= link_to 'Sign Out', destroy_user_session_path, class: "", :method => :delete  %></li>
                      </li>
                    </ul>
              </li>
            </ul>
        <% end %>
      </div>
    </div>
    </nav>

    <div class="carousel slide carousel-fade " id="mycarousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-slide-to="0" data-target="#mycarousel" class="active">
        </li>
        <li data-slide-to="1" data-target="#mycarousel">
        </li>
        <li data-slide-to="2" data-target="#mycarousel">
        </li>
      </ol>

      <div class="carousel-inner" role="listbox">
        <% @movies.order('id DESC').limit(3).each_with_index do |f,index| %>
            <div class="item <%= imglast(index)%>">
              <%= image_tag(f.image_url, alt: "f.title", class: "centeralign image1")%>
              <!-- <div class="covertext">
              <div class="col-lg-10" style="float:none; margin:0 auto;">
                <h1 class="title"><%=f.title%></h1>
                <div class="col-xs-12 explore">
                  <a href="<% movie_path(f)%>"><button type="button" class="btn btn-lg explorebtn">View</button></a>
                </div> -->

              <!-- <div class="carousel-caption">
                <h4><b><i>
                  <%= f.title %>
                </i></b></h4>
              </div> -->

            <!-- </div>
      </div> -->

      <!-- <a class="left carousel-control" href="#mycarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span></a>
        <a class="right carousel-control" href="#mycarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span></a> -->
    </div>
    <% end %>
    </div>
  </div>
  </div>